subdir-ccflags-y += -I$(srctree)/drivers/staging/android/ion/
subdir-ccflags-y += -I$(srctree)/drivers/iommu/
subdir-ccflags-y += -I$(srctree)/drivers/osal/linux/inc/
subdir-ccflags-y += -mno-outline-atomics

obj-$(CONFIG_VIDEO_HOBOTC_VPU) += vpu/
obj-$(CONFIG_VIDEO_HOBOTC_JPU) += jpg/
