# SPDX-License-Identifier: GPL-2.0-only

ccflags-y +=  -I$(srctree)/drivers/power/hobot/

obj-$(CONFIG_X5_CLK) += clk-external-io.o
obj-$(CONFIG_X5_CLK) += clk-snps-pll.o
obj-$(CONFIG_X5_CLK) += clk-generator.o
obj-$(CONFIG_X5_CLK) += clk-gate.o
obj-$(CONFIG_X5_CLK) += clk-x5.o
obj-$(CONFIG_X5_CLK) += clk-cpu.o
