# SPDX-License-Identifier: GPL-2.0-only
# SYNOPSYS Platform Support
archband_pdm-objs := archband-pdm.o hobot-i2s-dma-x5.o hobot-platform-x5.o
obj-$(CONFIG_SND_ARCHBAND_PDM) += archband_pdm.o
obj-$(CONFIG_SND_VIRT_CODEC) += virt-codec.o
