#
# Makefile for the Hobot X2network device drivers.
#

obj-$(CONFIG_X2_ETH) += hboot_eth_x2.o

obj-$(CONFIG_X3_ETH) := hobot_xj3_ethX.o
hobot_xj3_ethX-objs := hobot_eth.o hobot_mmc.o hobot_ethtool.o

obj-$(CONFIG_X5_ETH) := hobot_x5_ethX.o
hobot_x5_ethX-objs := hobot_eth.o hobot_mmc.o hobot_ethtool.o
