# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the Linux Kernel HOBOT SOC specific device drivers.
#

obj-$(CONFIG_HOBOT_BPU)                 += bpu/
obj-y                                   += socinfo/
obj-y                                   += reboot_reason/
obj-y                                   += ddr_monitor/
obj-y                                   += firewall/
obj-y                                   += camera_power/
obj-y                                   += vdsp/
